version: '3'

services:
  db:
    image: postgres:12.2-alpine
    container_name: "comments_db"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=value
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks: 
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "comment_api"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DB=postgres
      - DB_HOST=db
      - DB_TABLE=postgres
      - DB_PORT=5432
      - SSL_MODE=disable
    networks:
      - fullstack
    depends_on:
      - db

networks:
  fullstack:
    driver: bridge

volumes:
  database_postgres:
